title: sAIfer Lab Cybersecurity
description: Research in AI security, malware analysis, digital forensics, and resilient systems.
url: "https://saiferlab-cyber.github.io"
baseurl: ""
lang: en
timezone: Europe/Rome

markdown: kramdown
permalink: pretty

collections:
  theses:
    output: true
    permalink: /thesis/:name/

defaults:
  - scope:
      path: ""
      type: theses
    values:
      layout: thesis

exclude:
  - README.md
  - INSTALL.md
  - Gemfile
  - Gemfile.lock
